insert into upload_streamers(
        template_name,
        user,
        copyright,
        source,
        tid,
        cover,
        title,
        'desc',
        dynamic,
        tag,
        dtime,
        interactive,
        mission_id,
        dolby,
        lossless_music,
        no_reprint,
        open_elec,
        up_selection_reply,
        up_close_reply,
        up_close_danmu
    )
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20)
returning
    id,
    template_name as "template_name!",
    user as "user!",
    copyright as "copyright!: u8",
    source as "source!",
    tid as "tid!: u16",
    cover as "cover!",
    title as "title!",
    "desc" as "desc!",
    dynamic as "dynamic!",
    tag as "tag!",
    dtime as "dtime: u32",
    interactive as "interactive!: u8",
    mission_id as "mission_id: u32",
    dolby as "dolby!: u8",
    lossless_music as "lossless_music!: u8",
    no_reprint as "no_reprint: u8",
    open_elec as "open_elec: u8",
    up_selection_reply as "up_selection_reply!: bool",
    up_close_reply as "up_close_reply!: bool",
    up_close_danmu as "up_close_danmu!: bool"
